version: '3.9'

services:
  postgres:
    container_name: sentinel-postgres-14
    image: postgres:14
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ~/docker-volumes/sentinel-postgres-14:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - sentinel-net

  redis:
    container_name: sentinel-redis
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    env_file:
      - docker.env
    networks:
      - sentinel-net

networks:
  sentinel-net:
    driver: bridge
